"""empty message

Revision ID: 028d1ae71a59
Revises: 37563f6645ca
Create Date: 2022-08-20 11:09:48.529752

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '028d1ae71a59'
down_revision = '37563f6645ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('todos2')
    op.drop_table('todolists')
    op.drop_table('shows1')
    op.alter_column('Venue', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('Venue', 'city',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('Venue', 'state',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('Venue', 'address',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('Venue', 'phone',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('Venue', 'genres',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('Venue', 'image_link',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('Venue', 'facebook_link',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('Venue', 'website_link',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('Venue', 'seeking_talent',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('Venue', 'seeking_description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('shows', 'show_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_constraint('shows_artist_id_fkey', 'shows', type_='foreignkey')
    op.create_foreign_key(None, 'shows', 'Venue', ['venue_id'], ['id'])
    op.create_foreign_key(None, 'shows', 'Artist', ['artist_id'], ['id'])
    op.drop_column('shows', 'num_id')
    op.drop_column('shows', 'shows_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('shows_id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.add_column('shows', sa.Column('num_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'shows', type_='foreignkey')
    op.drop_constraint(None, 'shows', type_='foreignkey')
    op.create_foreign_key('shows_artist_id_fkey', 'shows', 'Artist', ['num_id'], ['id'])
    op.alter_column('shows', 'show_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('Venue', 'seeking_description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('Venue', 'seeking_talent',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('Venue', 'website_link',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('Venue', 'facebook_link',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('Venue', 'image_link',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('Venue', 'genres',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('Venue', 'phone',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('Venue', 'address',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('Venue', 'state',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('Venue', 'city',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('Venue', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_table('shows1',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('venue_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('artist_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('show_date', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='shows1_pkey')
    )
    op.create_table('todolists',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('todolists_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='todolists_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('todos2',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('completed', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('list_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['list_id'], ['todolists.id'], name='todos2_list_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='todos2_pkey')
    )
    # ### end Alembic commands ###
