"""empty message

Revision ID: b46b847f24fb
Revises: 9937d7333cce
Create Date: 2022-08-01 16:37:48.159747

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b46b847f24fb'
down_revision = '9937d7333cce'
branch_labels = None
depends_on = None



    # ### commands auto generated by Alembic - please adjust! ###
   
   # op.drop_column('todos', 'completed')

    
   
    # ### end Alembic commands ###



    # ### commands auto generated by Alembic - please adjust! ###
   # op.add_column('todos', sa.Column('completed', sa.BOOLEAN(), autoincrement=False, nullable=False))
   
   # ### end Alembic commands ###
